### ISSUE TITLE
Flogo app not working when exported from flogo web

### ISSUE THREAD

**Issue by nareshkumarthota** [TIBCOSoftware/flogo-cli#86]
I have created flogo app using flogo web. It contains simple Rest trigger with Rest invoker and Reply to trigger legacy one. I am not getting output in browser. Attached flogo.json for reference.

Steps to reproduce:
1. Create flogo app with attached json and start the binary.
2. Open browser hit the "url http://localhost:9096/pet/1"
3. I am getting empty page check the attached error.jpg

Observation:
I have changed output params value to null instead of empty array in metadata section. I can see the response in browser.
[flogo-err.zip](https://github.com/TIBCOSoftware/flogo-cli/files/1707297/flogo-err.zip)

**Comment by retgits** [comment]
Closing this issue as the legacy "reply" activity is no longer valid (has been replaced with the "return" activity) and the app model used in this sample is deprecated as well. Because I do want to make sure you have a valid sample to look at if you still need it, attached is a working version of what your app did as well with the most current app model.

[sample_app.json.zip](https://github.com/TIBCOSoftware/flogo-cli/files/2060501/sample_app.json.zip)
